add quality gate & fix bun error when running cairn build command
- linting, typecheck, security scanning, and full-corpus non-regression tests 
- fixed error "layout error: Cannot find module 'elkjs/lib/elk-worker.min.js' from '/$bunfs/root/cairn-1.0.0-RC04-darwin-arm64'" when running `cairn build` command